// <auto-generated />
using System;
using System.Collections.Generic;
using CharacterManagement.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CharacterManagement.Api.Migrations
{
    [DbContext(typeof(CharacterManagementContext))]
    [Migration("20240224202248_RemoveRaceNameEffectAndAddSizeEffect")]
    partial class RemoveRaceNameEffectAndAddSizeEffect
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterManagement.Api.Models.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TraitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("TraitId");

                    b.ToTable("Effect");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("SourceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.Trait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Trait");
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("RaceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.TraitEffects.SizeEffect", b =>
                {
                    b.HasBaseType("CharacterManagement.Api.Models.Effect");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.ToTable("SizeEffects", (string)null);
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Effect", b =>
                {
                    b.HasOne("CharacterManagement.Api.Models.Characters.Character", null)
                        .WithMany("Effects")
                        .HasForeignKey("CharacterId");

                    b.HasOne("CharacterManagement.Api.Models.Races.Trait", null)
                        .WithMany("Effects")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.Trait", b =>
                {
                    b.HasOne("CharacterManagement.Api.Models.Races.Race", null)
                        .WithMany("Traits")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.TraitEffects.SizeEffect", b =>
                {
                    b.HasOne("CharacterManagement.Api.Models.Effect", null)
                        .WithOne()
                        .HasForeignKey("CharacterManagement.Api.Models.Races.TraitEffects.SizeEffect", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Characters.Character", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.Race", b =>
                {
                    b.Navigation("Traits");
                });

            modelBuilder.Entity("CharacterManagement.Api.Models.Races.Trait", b =>
                {
                    b.Navigation("Effects");
                });
#pragma warning restore 612, 618
        }
    }
}
